* [0/4] Incorporate [[http://twitter.github.io/bootstrap/][Twitter Bootstrap]]'s CSS style sheets and JavaScript scripts.

  The heart of Twitter Bootstrap is two files: [[https://github.com/twitter/bootstrap/blob/master/docs/assets/css/bootstrap.css][bootstrap.css]] and [[https://github.com/twitter/bootstrap/blob/master/docs/assets/js/bootstrap.js][bootstrap.js]]. We copy
  the minified forms of those files ( bootstrap.min.css and bootstrap.min.js ) to our
  Rails application structure and Rails will detect and incorporate them into the application.
  
  1. [ ] Download the Zipfile from Twitter Bootstrap website from your web browser or web client.
     #+BEGIN_SRC sh :tangle bin/fetch-bootstrap-zip.sh :shebang #!/bin/sh
       # ./bin/fetch-bootstrap-zip.sh
       wget http://twitter.github.io/bootstrap/assets/bootstrap.zip
     #+END_SRC
  2. [ ] Decompress the bootstrap.zip Zip file
     #+BEGIN_SRC sh
       unzip bootstrap.zip
     #+END_SRC
  3. [ ] Copy the Bootstrap CSS and Javascript files to our Rails application structure
     #+BEGIN_SRC sh :tangle bin/copy-bootstrap-to-rails.sh :shebang #!/bin/sh
       # ./bin/copy-bootstrap-to-rails.sh
       mkdir -v ../app/assets/stylesheets/bootstrap
       cp -iv bootstrap/css/bootstrap.css ../app/assets/stylesheets/bootstrap/
       cp -iv bootstrap/css/bootstrap-responsive.css ../app/assets/stylesheets/bootstrap/
       cp -iv bootstrap/js/bootstrap.min.js ../app/assets/javascripts/

     #+END_SRC
  4. [ ] Copy glyphicons-halflings.png and glyphicons-halflings-white.png
     #+BEGIN_SRC sh :tangle bin/copy-images-to-rails.sh :shebang #!/bin/sh
       # ./bin/copy-bootstrap-to-rails.sh
       mkdir -v ../app/assets/images
       cp -iv bootstrap/img/glyphicons-halflings.png ../app/assets/images/
       cp -iv bootstrap/img/glyphicons-halflings-white.png ../app/assets/images/
     #+END_SRC
     
  Now that we have [[https://github.com/twitter/bootstrap/blob/master/docs/assets/css/bootstrap.css][bootstrap.css]] and [[https://github.com/twitter/bootstrap/blob/master/docs/assets/js/bootstrap.js][bootstrap.js]] incorporated into our Rails
  application we can proceed to change the default Rails application layout
  to use Bootstrap's CSS and Javascript.
  
* [0/2] Use Twitter Bootstrap fixed width layout in our Rails application

  Now that Bootstrap is installed let's proceed to use Bootstrap's CSS in our application.

  1. [ ] Overwrite app/views/layouts/application.html.erb with [[file:app/views/layouts/starter-template.html.erb][starter-template.html.erb]] 

     #+BEGIN_SRC sh :tangle bin/copy-starter-template.sh :shebang #!/bin/sh
       # ./bin/copy-starter-template.sh
       # this command will replace the default rails layout with a Twitter Bootstrap layout
       cp -v app/views/layouts/starter-template.html.erb ../app/views/layouts/application.html.erb
     #+END_SRC
     
     [[file:app/views/layouts/starter-template.html.erb][starter-template.html.erb]] is Twitter Bootstrap's [[https://github.com/twitter/bootstrap/blob/master/docs/examples/starter-template.html][starter template]] example merged
     with the default [[file:app/views/layouts/application.html.erb][app/views/layouts/application.html.erb]] file that Rails generates.
     
     Here's the resulting app/views/layouts/application.html.erb:
     #+BEGIN_SRC html
       <html>
       <head>
         <title>Bootstrap</title>
         <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
         <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
         <%= csrf_meta_tags %>
         <style>
           body {
           padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
           }
         </style>  
       </head>
       
           <body>
           
             <div class="navbar navbar-inverse navbar-fixed-top">
               <div class="navbar-inner">
                 <div class="container">
                   <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                   </button>
                   <a class="brand" href="#">Project name</a>
                   <div class="nav-collapse collapse">
                     <ul class="nav">
                       <li class="active"><a href="#">Home</a></li>
                       <li><a href="#about">About</a></li>
                       <li><a href="#contact">Contact</a></li>
                     </ul>
                   </div><!--/.nav-collapse -->
                 </div>
               </div>
             </div>
             <div class="container">
               
               <h1>Bootstrap starter template</h1>
               <p>Use this document as a way to quick start any new project.<br> All you get is this message and a barebones HTML document.</p>
               <%= yield %>
               
             </div> <!-- /container -->
             
           </body>
       
       
       </body>
       </html>
     #+END_SRC

     The starter example layout uses a fixed width layout, which is introduced at [[http://twitter.github.io/bootstrap/scaffolding.html#layouts][scaffolding.html#layouts]].
  2. [ ] Compare our application at http://localhost:3000 with http://twitter.github.io/bootstrap/examples/starter-template.html.
     
     Our newly created Rails application running on port 3000 should have essentially the
     same appearance as the example running on Twitter's github.io site. It it doesn't something
     went wrong.
* CSS, Sass, and LESS
* Attic
  - How to clone bootstrap
     #+BEGIN_SRC sh
       git clone https://github.com/twitter/bootstrap.git
       cp bootstrap/bootstrap.css path/to/app/assets/stylesheets/
     #+END_SRC
  - Article [[http://rubysource.com/twitter-bootstrap-less-and-sass-understanding-your-options-for-rails-3-1/][Twitter Bootstrap, Less, and Sass]]
