* Introduction
  
  This is a step by step tutorial for new Rails learners to learn how
  [[http://getbootstrap.com][Twitter Bootstrap]] works and to how to use Twitter Bootstrap to provide
  your application with modern layout and styling. This tutorial was last
  tested on July 29, 2014 by [[https://github.com/troywill][Troy Will]]. We will build a working
  Rails application to match the [[http://getbootstrap.com/examples/starter-template/][starter-template]] template from [[http://getbootstrap.com/getting-started/#examples][example layouts]]. 

  Note for Emacs users: This tutorial was written in Emacs Org Mode. If
  you are an Emacs Org Mode user you can carry out the steps in this tutorial
  from the twitter-bootstrap-step-by-step.org file.

* TODO Milestone 1: Build an initial Rails application

  Let's build our example Rails application with a 'home' controller
  and 'home/index', "home/about", "home/contact" pages since those pages
  are in the [[http://getbootstrap.com/2.3.2/examples/starter-template.html][starter-template.html]] template.
  
  1. [ ] Initialize a new Rails application
     #+BEGIN_SRC sh
       rails new example
     #+END_SRC
  2. [ ] Change into the newly created Rails application directory
     #+BEGIN_SRC sh
       cd example
     #+END_SRC
  3. [ ] Copy this twitter-bootstrap-step-by-step.org file
     #+BEGIN_SRC sh
       cp ../twitter-bootstrap-step-by-step.org .
     #+END_SRC
  4. [ ] Examine your Rails installation
     #+BEGIN_SRC sh
       rake about
     #+END_SRC
  5. [ ] Enable a JavaScript runtime in [[file:Gemfile][Gemfile]]
     
     You probably got a 'Could not find a JavaScript runtime.' message from the
     'rake about' command. Open [[file:../Gemfile][Gemfile]] with your text editor and enable 'therubyracer.'
     
     #+BEGIN_SRC ruby
       # See https://github.com/sstephenson/execjs#readme for more supported runtimes
       gem 'therubyracer', platforms: :ruby
     #+END_SRC
     
     You might open [[file:../Gemfile][Gemfile]] with Emacs, Vi, [[http://macromates.com/][TextMate]], etc. this way:
     #+BEGIN_EXAMPLE
       textmate Gemfile
     #+END_EXAMPLE
  6. [ ] Examine your Rails installation again
     #+BEGIN_SRC sh
       rake about
     #+END_SRC
  7. [ ] Create a “home” controller and “home/index”, "home/about", "home/contact" pages
     #+BEGIN_SRC sh :tangle bin/generate-controller-home.sh :shebang #!/bin/sh
       rails generate controller home index about contact --skip-stylesheets
     #+END_SRC
     
     Note the use of '--skip-stylesheets' since we will use Twitter Bootstrap's stylesheets
  8. [ ] Set the default route to home/index in [[file:config/routes.rb][config/routes.rb]]
     
     Open [[file:config/routes.rb][config/routes.rb]]  with your text editor. You will see the following
     commented line near the top of the file:
     #+BEGIN_SRC ruby
       # root 'welcome#index'
     #+END_SRC
     
     Let's uncomment and change the application root view:

     #+BEGIN_SRC ruby
       root "home#index"
     #+END_SRC
     
     Now, Rails will direct vistors to the application to home/index. We are
     ready to start the Rails application and incorporate Twitter Bootstrap's
     stylesheets and JavaScript scripts.
  9. [ ] Start the rails server
     #+BEGIN_SRC sh
       rails server --port 3000
     #+END_SRC

  Now, let's incorporate Bootstrap into our application.
* TODO Milestone 2: Set up Twitter Bootstrap with the [[https://github.com/thomas-mcdonald/bootstrap-sass/blob/master/README.md#bootstrap-for-sass][bootstrap-sass]] gem
  1. [ ] Enable [[http://rubygems.org/gems/bootstrap-sass][bootstrap-sass]] in file:Gemfile
     #+BEGIN_SRC ruby
       # See http://rubygems.org/gems/bootstrap-sass (August 1, 2014)
       gem "bootstrap-sass", "~> 3.2.0.1"
     #+END_SRC
  2. [ ] run bundle install
  3. [ ] Remove the app/assets/stylesheets/application.css file
     #+BEGIN_SRC sh
       rm -v app/assets/stylesheets/application.css
     #+END_SRC
  4. [ ] Create a new file:app/assets/stylesheets/application.css.scss file
     #+BEGIN_SRC css :tangle app/assets/stylesheets/application.css.scss :padline no
       @import "bootstrap";
       body { padding-top: 50px; }
     #+END_SRC
  5. [ ] Import bootstrap javascript in [[file:app/assets/javascripts/application.js][app/assets/javascripts/application.js]]
     #+BEGIN_SRC js
       //= require jquery
       //= require jquery_ujs
       //= require turbolinks
       //= require_tree .
       //
       // The following line Loads all Bootstrap javascripts
       // = require bootstrap
     #+END_SRC
* TODO Milestone 3: Use Twitter Bootstrap fixed width layout in our Rails application
  
  Now that Bootstrap is installed let's proceed to use Bootstrap's CSS in our application.

  1. [ ] Replace app/views/layouts/application.html.erb with

     Tangle the following file to [[file:app/views/layouts/application.html.erb]].
     #+BEGIN_SRC html :tangle app/views/layouts/application.html.erb :padline no

       <!DOCTYPE html>
       <html lang="en">
         <head>
           <title>Starter Template for Bootstrap</title>
           <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
           <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
           <%= csrf_meta_tags %>
           <style>
             body {
             padding-top: 50px; /* 50px to make the container go all the way to the bottom of the topbar */
             }
           </style>  
         </head>
         <body>
           <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
             <div class="container">
               <div class="navbar-header">
                 <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                   <span class="sr-only">Toggle navigation</span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                 </button>
                 <a class="navbar-brand" href="#">Project name</a>
               </div>
               <div class="collapse navbar-collapse">
                 <ul class="nav navbar-nav">
                   <li class="active"><a href="#">Home</a></li>
                   <li><a href="#about">About</a></li>
                   <li><a href="#contact">Contact</a></li>
                 </ul>
               </div><!--/.nav-collapse -->
             </div>
           </div>

           <div class="container">

             <div class="starter-template">
               <h1>Bootstrap starter template</h1>
               <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
               <%= yield %>
             </div>

           </div><!-- /.container -->
         </body>  

       </html>

     #+END_SRC
     
     The starter example layout uses a fixed width layout, which is introduced at [[http://twitter.github.io/bootstrap/scaffolding.html#layouts][scaffolding.html#layouts]].
  2. [ ] Compare our application at http://localhost:3000 with http://twitter.github.io/bootstrap/examples/starter-template.html.
     
     Our newly created Rails application running on port 3000 should have essentially the
     same appearance as the example running on Twitter's github.io site. It it doesn't something
     went wrong.

* Reference Section
** The most popular Rails Bootstrap Gems (August 2014)
  #+TBLNAME: bootstrap_gems
  | Gem                     | Version | Downloads | This version | Author          |
  |-------------------------+---------+-----------+--------------+-----------------|
  | [[http://rubygems.org/gems/bootstrap-sass][bootstrap-sass]]          | 3.2.0.1 | 4,244,000 |  7,000       | [[http://rubygems.org/profiles/tmcdonald][Thomas McDonald]] |
  | [[http://rubygems.org/gems/twitter-bootstrap-rails][twitter-bootstrap-rails]] |   2.2.8 | 1,326,000 | 350,000      | [[http://rubygems.org/profiles/seyhunak][Seyhun Akyurek]]  |
  | [[http://rubygems.org/gems/less-rails-bootstrap][less-rails-bootstrap]]    |   3.2.0 |   243,000 |   2,000      | [[http://rubygems.org/profiles/metaskills][Ken Collins]]     |
  | [[http://rubygems.org/gems/sass-twitter-bootstrap][sass-twitter-bootstrap]]  |   2.3.0 |     6,000 |   1,100      | [[http://rubygems.org/profiles/wadetandy][Wade Tandy]]      |
** Twitter Bootstrap GitHub
   | Link                                 | Description                             |
   |--------------------------------------+-----------------------------------------|
   | [[https://github.com/twbs/bootstrap]]    | The Twitter Bootstrap GitHub repository |
** http://devgirl.org/2012/08/06/styling-your-app-with-twitter-bootstrap/
   
