* Introduction
  
  This is a step by step tutorial for new Rails learners to learn how
  Twitter and Bootstrap works and to how to use Twitter Bootstrap to provide
  your application with modern layout and styling. We will build a working
  Rails application to match the [[http://twitter.github.io/bootstrap/examples/starter-template.html][starter-template.html]] template from
  [[http://twitter.github.io/bootstrap/getting-started.html#examples][getting-started.html#examples]].

  You can follow the steps below to create a working Rails application.

  Note for Emacs users: This tutorial was written in Emacs Org Mode. If
  you are an Emacs Org Mode user you can carry out the steps in this tutorial
  from the twitter-bootstrap-step-by-step.org file.
  
* Build an intial Rails application

  The [[http://twitter.github.io/bootstrap/index.html][Twitter Bootstrap project]] website provides [[http://twitter.github.io/bootstrap/getting-started.html#examples][8 example layouts]]. In this tutorial we
  will use the [[http://twitter.github.io/bootstrap/examples/starter-template.html][starter-template.html]] template to see how to use Bootstap's CSS layout.

  See [[http://twitter.github.io/bootstrap/][http://twitter.github.io/bootstrap/]] -> [[http://twitter.github.io/bootstrap/getting-started.html#examples][getting-started.html#examples]] to view all 8 examples.
  See [[https://github.com/twitter/bootstrap][Bootstrap GitHub Repository]] to view the developement repository.

  Let's build our example Rails application with a 'home' controller
  and 'home/index', "home/about", "home/contact" pages since those pages
  are in the [[http://twitter.github.io/bootstrap/examples/starter-template.html][starter-template.html]] template.
  
  1. [ ] Initialize a new Rails application
     #+BEGIN_SRC sh
       rails new bootstrap
     #+END_SRC
  2. [ ] Change into the newly created Rails application directory
     #+BEGIN_SRC sh
       cd bootstrap
     #+END_SRC
  3. [ ] Clone [[https://github.com/troywill/twitter-bootstrap-for-beginners][this tutorial]] from Github.
     #+BEGIN_SRC sh
       git clone https://github.com/troywill/twitter-bootstrap-for-beginners.git
     #+END_SRC
  4. [ ] Examine your Rails installation
     #+BEGIN_SRC sh
       rake about
     #+END_SRC
  5. [ ] Enable a JavaScript runtime in [[file:../Gemfile][Gemfile]]
     
     You probably got a 'Could not find a JavaScript runtime.' message from the
     'rake about' command. Open [[file:../Gemfile][Gemfile]] with your text editor and enable 'therubyracer.'
     
     #+BEGIN_SRC ruby
       # See https://github.com/sstephenson/execjs#readme for more supported runtimes
       gem 'therubyracer', platforms: :ruby
     #+END_SRC
     
     You might open [[file:../Gemfile][Gemfile]] with Emacs, Vi, [[http://macromates.com/][TextMate]], etc. this way:
     #+BEGIN_EXAMPLE
     textmate ../../Gemfile
     #+END_EXAMPLE
  6. [ ] Examine your Rails installation again
     #+BEGIN_SRC sh
       rake about
     #+END_SRC
  7. [ ] Create a “home” controller and “home/index”, "home/about", "home/contact" pages
     #+BEGIN_SRC sh
       rails generate controller home index about contact --skip-stylesheets
     #+END_SRC
     
     Note the use of '--skip-stylesheets' since we will use Twitter Bootstap's stylesheets
  8. [ ] Set the default route to home/index in [[file:../config/routes.rb][config/routes.rb]]
     
     Open [[file:../config/routes.rb][config/routes.rb]]  with your text editor. You will see the following
     two commented lines near the top of the file:
     #+BEGIN_SRC ruby
       # You can have the root of your site routed with "root"
       # root 'welcome#index'
     #+END_SRC
     # root 'welcome#index'
     
     Let's uncomment and change the root:

     #+BEGIN_SRC ruby
       root 'home#index'
     #+END_SRC
     
     Now, Rails will direct vistors to the application to home/index. We are
     ready to start the Rails application and incorporate Twitter Bootstap's
     stylesheets and JavaScript scripts.
  9. [ ] Start the rails server
     #+BEGIN_SRC sh
       rails server --port 3000
     #+END_SRC

  Now, let's incorporate Bootstrap into our application.
* [6/6] Incorporate [[http://twitter.github.io/bootstrap/][Twitter Bootstrap]]'s CSS style sheets and JavaScript scripts.

  The heart of Twitter Bootstrap is two files: [[https://github.com/twitter/bootstrap/blob/master/docs/assets/css/bootstrap.css][bootstrap.css]] and [[https://github.com/twitter/bootstrap/blob/master/docs/assets/js/bootstrap.js][bootstrap.js]]. We copy
  the minified forms of those files ( bootstrap.min.css and bootstrap.min.js ) to our
  Rails application structure and Rails will detect and incorporate them into the application.
  
  1. [X] Download the Zipfile from Twitter Bootstap website from your web browser or web client.
     #+BEGIN_SRC sh
       wget http://twitter.github.io/bootstrap/assets/bootstrap.zip
     #+END_SRC
  2. [X] Decompress the bootstrap.zip Zip file
     #+BEGIN_SRC sh
       unzip bootstrap.zip
     #+END_SRC
  3. [X] Copy bootstrap.min.css to app/assets/stylesheets
     #+BEGIN_SRC sh :tangle bin/copy-bootstap-to-rails
       cp -v bootstrap/css/bootstrap.css ../app/assets/stylesheets
     #+END_SRC
  4. [X] Copy bootstrap-repsonsive.min.css to app/assets/stylesheets
     #+BEGIN_SRC sh :tangle bin/copy-bootstap-to-rails
       cp -v bootstrap/css/bootstrap-responsive.css ../app/assets/stylesheets
     #+END_SRC
  5. [X] Copy bootstrap.min.js to app/assets/javascripts
     #+BEGIN_SRC sh :tangle bin/copy-bootstap-to-rails
       cp -iv bootstrap/js/bootstrap.min.js ../app/assets/javascripts
     #+END_SRC
  6. [X] Copy two image files
     #+BEGIN_SRC sh :tangle bin/copy-bootstap-to-rails
       # ‘bootstrap/img/glyphicons-halflings.png’
       # ‘bootstrap/img/glyphicons-halflings-white.png’
       
       mkdir -v ../app/assets/images
       cp -iv bootstrap/img/* ../app/assets/images/
     #+END_SRC
     
  Now that we have [[https://github.com/twitter/bootstrap/blob/master/docs/assets/css/bootstrap.css][bootstrap.css]] and [[https://github.com/twitter/bootstrap/blob/master/docs/assets/js/bootstrap.js][bootstrap.js]] incorporated into our Rails
  application we can proceed to change the default Rails application layout
  the use Bootstap's CSS and Javascript.
  
* [/] Use Twitter Bootstap's layout in our application instead of the default Rails layout

  The default Rails application layout resides in file:../app/views/layouts/. Two embedded
  ruby statements in the <head> section will pull in the Bootstap bootstrap.min.css and
  bootstrap.min.js code into the application:
  #+BEGIN_SRC html
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  #+END_SRC

  

  #+BEGIN_SRC html
    <body>
    
    <%= yield %>
    
    </body>
      
  #+END_SRC

  We will use the body stucture from Twitter Bootsrap's [[http://twitter.github.io/bootstrap/getting-started.html#examples][getting-started.html#examples]] / [[https://github.com/twitter/bootstrap/blob/master/docs/examples/starter-template.html][starter template]] example. The starter example layout may
  be viewed [[https://github.com/twitter/bootstrap/blob/master/docs/examples/starter-template.html][directly on GitHub]]. The starter example layout uses a fixed width layout, which is
  introduced at [[http://twitter.github.io/bootstrap/scaffolding.html#layouts][scaffolding.html#layouts]]. 

  #+BEGIN_SRC html
    <body>
      
      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="brand" href="#">Project name</a>
            <div class="nav-collapse collapse">
              <ul class="nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>
      <div class="container">
        
        <h1>Bootstrap starter template</h1>
        <p>Use this document as a way to quick start any new project.<br> All you get is this message and a barebones HTML document.</p>
        
      </div> <!-- /container -->
      
    </body>
  #+END_SRC

  1. [ ] Replace the <body><% = yield %></body> section with the Bootstrap <body> section in file:../app/views/layouts/application.html.erb
     
     Here's the end result:
     
     #+BEGIN_SRC html
       <html>
         <head>
           <title>Bootstrap</title>
           <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
           <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
           <%= csrf_meta_tags %>
           <style>
             body {
             padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
             }
           </style>  
         </head>
       
         <body>
           
           <div class="navbar navbar-inverse navbar-fixed-top">
             <div class="navbar-inner">
               <div class="container">
                 <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                 </button>
                 <a class="brand" href="#">Project name</a>
                 <div class="nav-collapse collapse">
                   <ul class="nav">
                     <li class="active"><a href="#">Home</a></li>
                     <li><a href="#about">About</a></li>
                     <li><a href="#contact">Contact</a></li>
                   </ul>
                 </div><!--/.nav-collapse -->
               </div>
             </div>
           </div>
           <div class="container">
             
             <h1>Bootstrap starter template</h1>
             <p>Use this document as a way to quick start any new project.<br> All you get is this message and a barebones HTML document.</p>
             <%= yield %>
             
           </div> <!-- /container -->
           
         </body>
       
       
       </body>
       </html>
     #+END_SRC
  
