* Introduction
  This is a step by step tutorial for new Rails learners to learn how
  Twitter and Bootstrap works and to how to use Twitter Bootstrap to provide
  your application with modern layout and styling.

  You can follow the steps below to create a working Rails application.

  Note for Emacs users: This tutorial was written in Emacs Org Mode. If
  you are an Emacs Org Mode user you can carry out the steps in this tutorial
  from the twitter-bootstrap-step-by-step.org file.
  
* Part One: Build an Rails application with

  The [[http://twitter.github.io/bootstrap/index.html][Twitter Bootstrap project]] on Github provides [[http://twitter.github.io/bootstrap/getting-started.html#examples][8 example layouts]]. In this tutorial we
  will use the [[http://twitter.github.io/bootstrap/examples/starter-template.html][starter-template.html]] template.

  See [[http://twitter.github.io/bootstrap/][http://twitter.github.io/bootstrap/]] -> [[http://twitter.github.io/bootstrap/getting-started.html#examples][getting-started.html#examples]] to view all 8 examples.

  Let's build our example Rails application with a 'home'
  controller and 'home/index', "home/about", "home/contact" pages to match the  [[http://twitter.github.io/bootstrap/examples/starter-template.html][starter-template.html]] template.
  
  1. [ ] Initialize a new Rails application
     #+BEGIN_SRC sh
       rails new bootstrap_tutorial
     #+END_SRC
  2. [ ] Change into the newly created Rails application directory
     #+BEGIN_SRC sh
       cd bootstrap_tutorial
     #+END_SRC
  3. [ ] Clone [[https://github.com/troywill/twitter-bootstrap-for-beginners][this tutorial]] from Github.
     #+BEGIN_SRC sh
       git clone https://github.com/troywill/twitter-bootstrap-for-beginners.git
     #+END_SRC
  4. [ ] Examine your Rails installation
     #+BEGIN_SRC sh
       rake about
     #+END_SRC
  5. [ ] Enable a JavaScript runtime in [[file:../Gemfile][Gemfile]]
     
     You probably got a 'Could not find a JavaScript runtime.' message from the
     'rake about' command. Open [[file:../Gemfile][Gemfile]] with your text editor and enable 'therubyracer.'
     
     #+BEGIN_SRC ruby
       # See https://github.com/sstephenson/execjs#readme for more supported runtimes
       gem 'therubyracer', platforms: :ruby
     #+END_SRC
     
     You might open [[file:../Gemfile][Gemfile]] with [[http://macromates.com/][TextMate]] this way:
     #+BEGIN_EXAMPLE
     textmate ../../Gemfile
     #+END_EXAMPLE
  6. [ ] Examine your Rails installation again
     #+BEGIN_SRC sh
       rake about
     #+END_SRC
  7. [ ] Create a “home” controller and “home/index”, "home/about", "home/contact" pages
     #+BEGIN_SRC sh
       rails generate controller home index about contact --skip-stylesheets
     #+END_SRC
     
     Note the use of '--skip-stylesheets' since we will use Twitter Bootstap's stylesheets
  8. [ ] Set the default route to home/index in [[file:../config/routes.rb][config/routes.rb]]
     
     Open [[file:../config/routes.rb][config/routes.rb]]  with your text editor. You will see the following
     two commented lines near the top of the file:
     #+BEGIN_SRC ruby
       # You can have the root of your site routed with "root"
       # root 'welcome#index'
     #+END_SRC
     # root 'welcome#index'
     
     Let's uncomment and change the root:

     #+BEGIN_SRC ruby
       root 'home#index'
     #+END_SRC
     
     Now, Rails will direct vistors to the application to home/index. We are
     ready to start the Rails application and incorporate Twitter Bootstap's
     stylesheets and JavaScript scripts.
  9. [ ] Start the rails server
     #+BEGIN_SRC sh
       rails server --port 3000
     #+END_SRC
* Part Two: Incorporate [[http://twitter.github.io/bootstrap/][Twitter Bootstrap]]'s CSS style sheets and JavaScript scripts.
